### ISSUE TITLE
Allow complex names in st-sort

### ISSUE THREAD

**Issue by mzealey** [lorenzofox3/Smart-Table#561]
Hi there, I'm creating some complex dynamic tables from data stored in a MongoDB database backend. The tables are 100% dynamic so all the sort etc is being handled server-side. In this case I don't want the st-sort data to be parsed cleverly as this leads to breakages. For example in Mongo if you have some data stored in a set of documents like "{ bar: [ { foo: 123 }] }" you can do a sort based on "bar.0.foo". But if I put this into the st-sort column, angular tries to parse this and crashes:

Error: [$parse:syntax] Syntax Error: Token '.0.' is an unexpected token at column 13 of the expression [bar.0.foo] starting at [.0.foo].
http://errors.angularjs.org/1.4.7/$parse/syntax?p0=.0.&p1=is%20an%20unexpected%20token&p2=13&p3=status_stats.0.ts&p4=.0.ts
    at http://localhost:3000/bower_components/angular/angular.js:68:12
    at Object.AST.throwError (http://localhost:3000/bower_components/angular/angular.js:13057:11)
    at Object.AST.ast (http://localhost:3000/bower_components/angular/angular.js:12827:12)
    at Object.ASTCompiler.compile (http://localhost:3000/bower_components/angular/angular.js:13276:31)
    at Parser.parse (http://localhost:3000/bower_components/angular/angular.js:14146:29)
    at $parse (http://localhost:3000/bower_components/angular/angular.js:14248:39)
    at link (http://localhost:3000/bower_components/angular-smart-table/dist/smart-table.js:333:22)

Could there be (or Is there already) some way to specify that st-sort fields are literals and should just be passed through to the backend rather than parsed first?

**Comment by lorenzofox3** [comment]
use quotes ? https://github.com/lorenzofox3/Smart-Table/issues/543
